# Generated by Django 3.0.8 on 2021-07-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobile_number', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
                ('Adhaar_number', models.IntegerField()),
                ('pancard_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('credit', models.IntegerField()),
                ('debit', models.IntegerField()),
                ('total', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bankmanagebackend.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='accountholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bankmanagebackend.AccountHolder'),
        ),
    ]
