# Generated by Django 3.0.8 on 2021-07-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0002_auto_20210715_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
