# Generated by Django 3.0.8 on 2021-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0004_auto_20210715_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholder',
            old_name='admin',
            new_name='manager',
        ),
    ]
