# Generated by Django 3.0.8 on 2021-07-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0005_auto_20210715_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='email_address',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
