# Generated by Django 3.0.8 on 2021-07-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0006_accountholder_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountholder',
            old_name='staff',
            new_name='client',
        ),
    ]
