# Generated by Django 3.0.8 on 2021-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0010_auto_20210720_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
