# Generated by Django 3.0.8 on 2021-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0011_remove_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
    ]
