# Generated by Django 3.0.8 on 2021-07-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0015_auto_20210720_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountholder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='Bankmanagebackend.AccountHolder'),
        ),
    ]
