# Generated by Django 3.0.8 on 2021-07-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0016_auto_20210721_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
