# Generated by Django 3.0.8 on 2021-07-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0017_auto_20210721_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='pancard_number',
            field=models.CharField(max_length=20),
        ),
    ]
