# Generated by Django 3.0.8 on 2021-07-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0018_auto_20210721_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
