# Generated by Django 3.0.8 on 2021-07-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0019_accountholder_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='token',
        ),
    ]
