# Generated by Django 3.0.8 on 2021-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankmanagebackend', '0020_remove_accountholder_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='client',
        ),
    ]
