const SIGNUP_SUCCESS="SIGNUP_SUCCESS";
const SIGNUP_FAILURE="SIGNUP_FAILURE";
const LOGIN_SUCCESS="LOGIN_SUCCESS";
const LOGIN_FAILURE="LOGIN_FAILURE";
const ACCOUNT_CREATE_SUCCESS="ACCOUNT_CREATE_SUCCESS";
const ACCOUNT_CREATE_FAILURE="ACCOUNT_CREATE_FAILURE";
const UPDATE_SELECTED_ACCOUNT="UPDATE_SELECTED_ACCOUNT";
const ACCOUNT_LOGS="ACCOUNT_LOGS";
const DEPOSIT_SUCCESS="DEPOSIT_SUCCESS";
const DEPOSIT_FAILURE="DEPOSIT_FAILURE";
const WITHDRAW_SUCCESS="WITHDRAW_SUCCESS";
const WITHDRAW_FAILURE="WITHDRAW_FAILURE";
const SEND_SUCCESS="SEND_SUCCESS";
const SEND_FAILURE="SEND_FAILURE";
const DELETE_SUCCESS="DELETE_SUCCESS";
const MANAGER_LOGIN_SUCCESS="MANAGER_LOGIN_SUCCESS";
const MANAGER_LOGIN_FAILURE="MANAGER_LOGIN_FAILURE";
const LOGOUT="LOGOUT";
const UPDATE_USER_ACCOUNTS="UPDATE_USER_ACCOUNTS"

export {SIGNUP_SUCCESS,SIGNUP_FAILURE,LOGIN_FAILURE,LOGIN_SUCCESS,ACCOUNT_CREATE_SUCCESS,ACCOUNT_CREATE_FAILURE,
    UPDATE_SELECTED_ACCOUNT,ACCOUNT_LOGS,DEPOSIT_SUCCESS,DEPOSIT_FAILURE, DELETE_SUCCESS,LOGOUT,UPDATE_USER_ACCOUNTS,
    WITHDRAW_SUCCESS,WITHDRAW_FAILURE,SEND_FAILURE,SEND_SUCCESS,MANAGER_LOGIN_FAILURE,MANAGER_LOGIN_SUCCESS}